ci: fixes syntax
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>

diff --git a/.pipelines/templates/e2e-arc-extension-test.yaml b/.pipelines/templates/e2e-arc-extension-test.yaml
--- a/.pipelines/templates/e2e-arc-extension-test.yaml
+++ b/.pipelines/templates/e2e-arc-extension-test.yaml
@@ -72,35 +72,35 @@ jobs:
         displayName: "connect KinD cluster"
         condition: succeeded()
       - script: |
-        az k8s-extension create \
-        --name ${AZURE_CLUSTER_NAME} \
-        --extension-type Microsoft.AzureKeyVaultSecretsProvider \
-        --scope cluster --cluster-name ${AZURE_CLUSTER_NAME} \
-        --resource-group ${AZURE_CLUSTER_NAME} \
-        --cluster-type connectedClusters --release-train dev \
-        --version $(EXT_VERSION) \
-        --release-namespace kube-system \
-        --configuration-settings 'secrets-store-csi-driver.enableSecretRotation=true' 'secrets-store-csi-driver.rotationPollInterval=30s' 'linux.image.tag=$(IMAGE_VERSION)' 'linux.image.repository=$(CI_REGISTRY)/$(CI_IMAGE_NAME)' 'secrets-store-csi-driver.syncSecret.enabled=true' 'linux.volumes[0].name=$(VOLUME_NAME)' 'linux.volumes[0].hostPath.path=$(AZURE_ENVIRONMENT_FILEPATH)' 'linux.volumes[0].hostPath.type=File' 'linux.volumeMounts[0].name=$(VOLUME_NAME)' 'linux.volumeMounts[0].mountPath=$(AZURE_ENVIRONMENT_FILEPATH)'
+          az k8s-extension create \
+          --name ${AZURE_CLUSTER_NAME} \
+          --extension-type Microsoft.AzureKeyVaultSecretsProvider \
+          --scope cluster --cluster-name ${AZURE_CLUSTER_NAME} \
+          --resource-group ${AZURE_CLUSTER_NAME} \
+          --cluster-type connectedClusters --release-train dev \
+          --version $(EXT_VERSION) \
+          --release-namespace kube-system \
+          --configuration-settings 'secrets-store-csi-driver.enableSecretRotation=true' 'secrets-store-csi-driver.rotationPollInterval=30s' 'linux.image.tag=$(IMAGE_VERSION)' 'linux.image.repository=$(CI_REGISTRY)/$(CI_IMAGE_NAME)' 'secrets-store-csi-driver.syncSecret.enabled=true' 'linux.volumes[0].name=$(VOLUME_NAME)' 'linux.volumes[0].hostPath.path=$(AZURE_ENVIRONMENT_FILEPATH)' 'linux.volumes[0].hostPath.type=File' 'linux.volumeMounts[0].name=$(VOLUME_NAME)' 'linux.volumeMounts[0].mountPath=$(AZURE_ENVIRONMENT_FILEPATH)'
 
-        # Arc extensions will go through different phases (Pending, Installed etc.) of installation. We want to make sure extension is 'Installed' before running e2e tests.
-        echo "verifying extension install status..."
-        for i in $(seq 1 25); do
-          installState=$(az k8s-extension show -c ${AZURE_CLUSTER_NAME} -t connectedClusters -n ${AZURE_CLUSTER_NAME} -g ${AZURE_CLUSTER_NAME} --query "installState" -otsv)
-          if [ "$installState" == "Installed" ]; then
-            echo "AzureKeyVaultSecretsProvider extension is 'Installed'"
-            break
-          else
-            echo "Install state - $installState"
-            sleep 1
+          # Arc extensions will go through different phases (Pending, Installed etc.) of installation. We want to make sure extension is 'Installed' before running e2e tests.
+          echo "verifying extension install status..."
+          for i in $(seq 1 25); do
+            installState=$(az k8s-extension show -c ${AZURE_CLUSTER_NAME} -t connectedClusters -n ${AZURE_CLUSTER_NAME} -g ${AZURE_CLUSTER_NAME} --query "installState" -otsv)
+            if [ "$installState" == "Installed" ]; then
+              echo "AzureKeyVaultSecretsProvider extension is 'Installed'"
+              break
+            else
+              echo "Install state - $installState"
+              sleep 1
+            fi
+          done
+
+          if [ "$installState" != "Installed" ]; then
+            echo "failed to install extension."
+            exit 1
           fi
-        done
 
-        if [ "$installState" != "Installed" ]; then
-          echo "failed to install extension."
-          exit 1
-        fi
-
-        helm ls -A
-      displayName: "install AzureKeyVaultSecretsProvider extension"
-      condition: succeeded()
+          helm ls -A
+        displayName: "install AzureKeyVaultSecretsProvider extension"
+        condition: succeeded()
       - template: teardown.yaml
